spring:
  datasource:
    url: jdbc:postgresql://balarama.db.elephantsql.com/bhbmmfvb
    username: bhbmmfvb
    password: 0dLuCYSKssaGYEgywIzJAOwF4WoyLL3C
  jpa:
    hibernate:
      ddl-auto: create
debug: true